name: Deploy on Successful Push to Main

on:
  workflow_dispatch:
  # workflow_run:
  #   workflows: ["Lint and Test"]
  #   types:
  #     - completed

jobs:
  deploy:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Deployment Webhook
        run: |
          curl --request GET '${{ secrets.COOLIFY_WEBHOOK }}' \
          --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'
